
name: roots_of_life
description: A simple Flutter app about mangroves.
publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.3

flutter:
  uses-material-design: true
